canadian_cities = [
["Toronto", "Ontario],
["Montr√©al", "Qu√©bec],
["Vancouver", "British Columbia],
["Ottawa", "Ontario],
["Calgary", "Alberta],
["Edmonton", "Alberta],
["Hamilton", "Ontario],
["Winnipeg", "Manitoba],
["Qu√©bec", "Qu√©bec],
["Oshawa", "Ontario],
["Kitchener", "Ontario],
["Halifax", "Nova Scotia],
["London", "Ontario],
["Windsor", "Ontario],
["Victoria", "British Columbia],
["Saskatoon", "Saskatchewan],
["Barrie", "Ontario],
["Regina", "Saskatchewan],
["Sudbury", "Ontario],
["Abbotsford", "British Columbia],
["Sarnia", "Ontario],
["Sherbrooke", "Qu√©bec],
["Saint John‚Äôs", "Newfoundland and Labrador],
["Kelowna", "British Columbia],
["Trois-Rivi√®res", "Qu√©bec],
["Kingston", "Ontario],
["Thunder Bay", "Ontario],
["Moncton", "New Brunswick],
["Saint John", "New Brunswick],
["Nanaimo", "British Columbia],
["Peterborough", "Ontario],
["Saint-J√©r√¥me", "Qu√©bec],
["Red Deer", "Alberta],
["Lethbridge", "Alberta],
["Kamloops", "British Columbia],
["Prince George", "British Columbia],
["Medicine Hat", "Alberta],
["Drummondville", "Qu√©bec],
["Chicoutimi", "Qu√©bec],
["Fredericton", "New Brunswick],
["Chilliwack", "British Columbia],
["North Bay", "Ontario],
["Shawinigan-Sud", "Qu√©bec],
["Cornwall", "Ontario],
["Joliette", "Qu√©bec],
["Belleville", "Ontario],
["Charlottetown", "Prince Edward Island],
["Victoriaville", "Qu√©bec],
["Grande Prairie", "Alberta],
["Penticton", "British Columbia],
["Sydney", "Nova Scotia],
["Orillia", "Ontario],
["Rimouski", "Qu√©bec],
["Timmins", "Ontario],
["Prince Albert", "Saskatchewan],
["Campbell River", "British Columbia],
["Courtenay", "British Columbia],
["Orangeville", "Ontario],
["Moose Jaw", "Saskatchewan],
["Brandon", "Manitoba],
["Brockville", "Ontario],
["Saint-Georges", "Qu√©bec],
["Sept-√éles", "Qu√©bec],
["Rouyn-Noranda", "Qu√©bec],
["Whitehorse", "Yukon],
["Owen Sound", "Ontario],
["Fort McMurray", "Alberta],
["Corner Brook", "Newfoundland and Labrador],
["Val-d‚ÄôOr", "Qu√©bec],
["New Glasgow", "Nova Scotia],
["Terrace", "British Columbia],
["North Battleford", "Saskatchewan],
["Yellowknife", "Northwest Territories],
["Fort Saint John", "British Columbia],
["Cranbrook", "British Columbia],
["Edmundston", "New Brunswick],
["Rivi√®re-du-Loup", "Qu√©bec],
["Camrose", "Alberta],
["Pembroke", "Ontario],
["Yorkton", "Saskatchewan],
["Swift Current", "Saskatchewan],
["Prince Rupert", "British Columbia],
["Williams Lake", "British Columbia],
["Brooks", "Alberta],
["Quesnel", "British Columbia],
["Thompson", "Manitoba],
["Dolbeau", "Qu√©bec],
["Powell River", "British Columbia],
["Wetaskiwin", "Alberta],
["Nelson", "British Columbia],
["Mont-Laurier", "Qu√©bec],
["Kenora", "Ontario],
["Dawson Creek", "British Columbia],
["Amos", "Qu√©bec],
["Baie-Comeau", "Qu√©bec],
["Hinton", "Alberta],
["Selkirk", "Manitoba],
["Steinbach", "Manitoba],
["Weyburn", "Saskatchewan],
["Amherst", "Nova Scotia],
["Kapuskasing", "Ontario],
["Dauphin", "Manitoba],
["Dryden", "Ontario],
["Revelstoke", "British Columbia],
["Happy Valley", "Newfoundland and Labrador],
["Banff", "Alberta],
["Yarmouth", "Nova Scotia],
["La Sarre", "Qu√©bec],
["Parry Sound", "Ontario],
["Stephenville", "Newfoundland and Labrador],
["Antigonish", "Nova Scotia],
["Flin Flon", "Manitoba],
["Fort Nelson", "British Columbia],
["Smithers", "British Columbia],
["Iqaluit", "Nunavut],
["Bathurst", "New Brunswick],
["The Pas", "Manitoba],
["Norway House", "Manitoba],
["Meadow Lake", "Saskatchewan],
["Vegreville", "Alberta],
["Stettler", "Alberta],
["Peace River", "Alberta],
["New Liskeard", "Ontario],
["Hearst", "Ontario],
["Creston", "British Columbia],
["Marathon", "Ontario],
["Cochrane", "Ontario],
["Kindersley", "Saskatchewan],
["Liverpool", "Nova Scotia],
["Melville", "Saskatchewan],
["Channel-Port aux Basques", "Newfoundland and Labrador],
["Deer Lake", "Newfoundland and Labrador],
["Saint-Augustin", "Qu√©bec],
["Digby", "Nova Scotia],
["Jasper", "Alberta],
["Hay River", "Northwest Territories],
["Windsor", "Nova Scotia],
["La Ronge", "Saskatchewan],
["Deer Lake", "Ontario],
["Gasp√©", "Qu√©bec],
["Atikokan", "Ontario],
["Gander", "Newfoundland and Labrador],
["Fort Chipewyan", "Alberta],
["Shelburne", "Nova Scotia],
["Inuvik", "Northwest Territories],
["Lac La Biche", "Alberta],
["Lillooet", "British Columbia],
["Chapleau", "Ontario],
["Burns Lake", "British Columbia],
["Gimli", "Manitoba],
["Athabasca", "Alberta],
["Nelson House", "Manitoba],
["Rankin Inlet", "Nunavut],
["Port Hardy", "British Columbia],
["Biggar", "Saskatchewan],
["Wiarton", "Ontario],
["Wawa", "Ontario],
["Hudson Bay", "Saskatchewan],
["Matagami", "Qu√©bec],
["Arviat", "Nunavut],
["Attawapiskat", "Ontario],
["Red Lake", "Ontario],
["Moosonee", "Ontario],
["Tofino", "British Columbia],
["Igloolik", "Nunavut],
["Inukjuak", "Qu√©bec],
["Little Current", "Ontario],
["Baker Lake", "Nunavut],
["Pond Inlet", "Nunavut],
["Cap-Chat", "Qu√©bec],
["Cambridge Bay", "Nunavut],
["Thessalon", "Ontario],
["New Bella Bella", "British Columbia],
["Cobalt", "Ontario],
["Cape Dorset", "Nunavut],
["Pangnirtung", "Nunavut],
["West Dawson", "Yukon],
["Kugluktuk", "Nunavut],
["Geraldton", "Ontario],
["Gillam", "Manitoba],
["Kuujjuaq", "Qu√©bec],
["Lake Louise", "Alberta],
["Nipigon", "Ontario],
["Nain", "Newfoundland and Labrador],
["Gjoa Haven", "Nunavut],
["Fort McPherson", "Northwest Territories],
["Argentia", "Newfoundland and Labrador],
["Norman Wells", "Northwest Territories],
["Churchill", "Manitoba],
["Repulse Bay", "Nunavut],
["Tuktoyaktuk", "Northwest Territories],
["Berens River", "Manitoba],
["Shamattawa", "Manitoba],
["Baddeck", "Nova Scotia],
["Coral Harbour", "Nunavut],
["La Scie", "Newfoundland and Labrador],
["Watson Lake", "Yukon],
["Taloyoak", "Nunavut],
["Natashquan", "Qu√©bec],
["Buchans", "Newfoundland and Labrador],
["Hall Beach", "Nunavut],
["Arctic Bay", "Nunavut],
["Fort Good Hope", "Northwest Territories],
["Mingan", "Qu√©bec],
["Kangirsuk", "Qu√©bec],
["Sandspit", "British Columbia],
["D√©lƒØne", "Northwest Territories],
["Fort Smith", "Northwest Territories],
["Cartwright", "Newfoundland and Labrador],
["Holman", "Northwest Territories],
["Lynn Lake", "Manitoba],
["Schefferville", "Qu√©bec],
["Trout River", "Newfoundland and Labrador],
["Forteau Bay", "Newfoundland and Labrador],
["Fort Resolution", "Northwest Territories],
["Hopedale", "Newfoundland and Labrador],
["Pukatawagan", "Manitoba],
["Trepassey", "Newfoundland and Labrador],
["Kimmirut", "Nunavut],
["Chesterfield Inlet", "Nunavut],
["Eastmain", "Qu√©bec],
["Dease Lake", "British Columbia],
["Paulatuk", "Northwest Territories],
["Fort Simpson", "Northwest Territories],
["Brochet", "Manitoba],
["Cat Lake", "Ontario],
["Radisson", "Qu√©bec],
["Port-Menier", "Qu√©bec],
["Resolute", "Nunavut],
["Saint Anthony", "Newfoundland and Labrador],
["Port Hope Simpson", "Newfoundland and Labrador],
["Oxford House", "Manitoba],
["Tsiigehtchic", "Northwest Territories],
["Ivujivik", "Qu√©bec],
["Stony Rapids", "Saskatchewan],
["Alert", "Nunavut],
["Fort Severn", "Ontario],
["Rigolet", "Newfoundland and Labrador],
["Lansdowne House", "Ontario],
["Salluit", "Qu√©bec],
["≈Åutselk‚Äôe", "Northwest Territories],
["Uranium City", "Saskatchewan],
["Burwash Landing", "Yukon],
["Grise Fiord", "Nunavut],
["Big Beaverhouse", "Ontario],
["Island Lake", "Manitoba],
["Ennadai", "Nunavut"]
]