@canadian_cities = [
["Toronto", "Ontario"],
["Montreal", "Quebec"],
["Vancouver", "British Columbia"],
["Ottawa", "Ontario"],
["Calgary", "Alberta"],
["Edmonton", "Alberta"],
["Hamilton", "Ontario"],
["Winnipeg", "Manitoba"],
["Quebec", "Quebec"],
["Oshawa", "Ontario"],
["Kitchener", "Ontario"],
["Halifax", "Nova Scotia"],
["London", "Ontario"],
["Windsor", "Ontario"],
["Victoria", "British Columbia"],
["Saskatoon", "Saskatchewan"],
["Barrie", "Ontario"],
["Regina", "Saskatchewan"],
["Sudbury", "Ontario"],
["Abbotsford", "British Columbia"],
["Sarnia", "Ontario"],
["Sherbrooke", "Quebec"],
["Saint John‚Äôs", "Newfoundland and Labrador"],
["Kelowna", "British Columbia"],
["Trois-Rivi√®res", "Quebec"],
["Kingston", "Ontario"],
["Thunder Bay", "Ontario"],
["Moncton", "New Brunswick"],
["Saint John", "New Brunswick"],
["Nanaimo", "British Columbia"],
["Peterborough", "Ontario"],
["Saint-Jereme", "Quebec"],
["Red Deer", "Alberta"],
["Lethbridge", "Alberta"],
["Kamloops", "British Columbia"],
["Prince George", "British Columbia"],
["Medicine Hat", "Alberta"],
["Drummondville", "Quebec"],
["Chicoutimi", "Quebec"],
["Fredericton", "New Brunswick"],
["Chilliwack", "British Columbia"],
["North Bay", "Ontario"],
["Shawinigan-Sud", "Quebec"],
["Cornwall", "Ontario"],
["Joliette", "Quebec"],
["Belleville", "Ontario"],
["Charlottetown", "Prince Edward Island"],
["Victoriaville", "Quebec"],
["Grande Prairie", "Alberta"],
["Penticton", "British Columbia"],
["Sydney", "Nova Scotia"],
["Orillia", "Ontario"],
["Rimouski", "Quebec"],
["Timmins", "Ontario"],
["Prince Albert", "Saskatchewan"],
["Campbell River", "British Columbia"],
["Courtenay", "British Columbia"],
["Orangeville", "Ontario"],
["Moose Jaw", "Saskatchewan"],
["Brandon", "Manitoba"],
["Brockville", "Ontario"],
["Saint-Georges", "Quebec"],
["Sept-√éles", "Quebec"],
["Rouyn-Noranda", "Quebec"],
["Whitehorse", "Yukon"],
["Owen Sound", "Ontario"],
["Fort McMurray", "Alberta"],
["Corner Brook", "Newfoundland and Labrador"],
["Val-d‚ÄôOr", "Quebec"],
["New Glasgow", "Nova Scotia"],
["Terrace", "British Columbia"],
["North Battleford", "Saskatchewan"],
["Yellowknife", "Northwest Territories"],
["Fort Saint John", "British Columbia"],
["Cranbrook", "British Columbia"],
["Edmundston", "New Brunswick"],
["Rivi√®re-du-Loup", "Quebec"],
["Camrose", "Alberta"],
["Pembroke", "Ontario"],
["Yorkton", "Saskatchewan"],
["Swift Current", "Saskatchewan"],
["Prince Rupert", "British Columbia"],
["Williams Lake", "British Columbia"],
["Brooks", "Alberta"],
["Quesnel", "British Columbia"],
["Thompson", "Manitoba"],
["Dolbeau", "Quebec"],
["Powell River", "British Columbia"],
["Wetaskiwin", "Alberta"],
["Nelson", "British Columbia"],
["Mont-Laurier", "Quebec"],
["Kenora", "Ontario"],
["Dawson Creek", "British Columbia"],
["Amos", "Quebec"],
["Baie-Comeau", "Quebec"],
["Hinton", "Alberta"],
["Selkirk", "Manitoba"],
["Steinbach", "Manitoba"],
["Weyburn", "Saskatchewan"],
["Amherst", "Nova Scotia"],
["Kapuskasing", "Ontario"],
["Dauphin", "Manitoba"],
["Dryden", "Ontario"],
["Revelstoke", "British Columbia"],
["Happy Valley", "Newfoundland and Labrador"],
["Banff", "Alberta"],
["Yarmouth", "Nova Scotia"],
["La Sarre", "Quebec"],
["Parry Sound", "Ontario"],
["Stephenville", "Newfoundland and Labrador"],
["Antigonish", "Nova Scotia"],
["Flin Flon", "Manitoba"],
["Fort Nelson", "British Columbia"],
["Smithers", "British Columbia"],
["Iqaluit", "Nunavut"],
["Bathurst", "New Brunswick"],
["The Pas", "Manitoba"],
["Norway House", "Manitoba"],
["Meadow Lake", "Saskatchewan"],
["Vegreville", "Alberta"],
["Stettler", "Alberta"],
["Peace River", "Alberta"],
["New Liskeard", "Ontario"],
["Hearst", "Ontario"],
["Creston", "British Columbia"],
["Marathon", "Ontario"],
["Cochrane", "Ontario"],
["Kindersley", "Saskatchewan"],
["Liverpool", "Nova Scotia"],
["Melville", "Saskatchewan"],
["Channel-Port aux Basques", "Newfoundland and Labrador"],
["Deer Lake", "Newfoundland and Labrador"],
["Saint-Augustin", "Quebec"],
["Digby", "Nova Scotia"],
["Jasper", "Alberta"],
["Hay River", "Northwest Territories"],
["Windsor", "Nova Scotia"],
["La Ronge", "Saskatchewan"],
["Deer Lake", "Ontario"],
["Gaspe", "Quebec"],
["Atikokan", "Ontario"],
["Gander", "Newfoundland and Labrador"],
["Fort Chipewyan", "Alberta"],
["Shelburne", "Nova Scotia"],
["Inuvik", "Northwest Territories"],
["Lac La Biche", "Alberta"],
["Lillooet", "British Columbia"],
["Chapleau", "Ontario"],
["Burns Lake", "British Columbia"],
["Gimli", "Manitoba"],
["Athabasca", "Alberta"],
["Nelson House", "Manitoba"],
["Rankin Inlet", "Nunavut"],
["Port Hardy", "British Columbia"],
["Biggar", "Saskatchewan"],
["Wiarton", "Ontario"],
["Wawa", "Ontario"],
["Hudson Bay", "Saskatchewan"],
["Matagami", "Quebec"],
["Arviat", "Nunavut"],
["Attawapiskat", "Ontario"],
["Red Lake", "Ontario"],
["Moosonee", "Ontario"],
["Tofino", "British Columbia"],
["Igloolik", "Nunavut"],
["Inukjuak", "Quebec"],
["Little Current", "Ontario"],
["Baker Lake", "Nunavut"],
["Pond Inlet", "Nunavut"],
["Cap-Chat", "Quebec"],
["Cambridge Bay", "Nunavut"],
["Thessalon", "Ontario"],
["New Bella Bella", "British Columbia"],
["Cobalt", "Ontario"],
["Cape Dorset", "Nunavut"],
["Pangnirtung", "Nunavut"],
["West Dawson", "Yukon"],
["Kugluktuk", "Nunavut"],
["Geraldton", "Ontario"],
["Gillam", "Manitoba"],
["Kuujjuaq", "Quebec"],
["Lake Louise", "Alberta"],
["Nipigon", "Ontario"],
["Nain", "Newfoundland and Labrador"],
["Gjoa Haven", "Nunavut"],
["Fort McPherson", "Northwest Territories"],
["Argentia", "Newfoundland and Labrador"],
["Norman Wells", "Northwest Territories"],
["Churchill", "Manitoba"],
["Repulse Bay", "Nunavut"],
["Tuktoyaktuk", "Northwest Territories"],
["Berens River", "Manitoba"],
["Shamattawa", "Manitoba"],
["Baddeck", "Nova Scotia"],
["Coral Harbour", "Nunavut"],
["La Scie", "Newfoundland and Labrador"],
["Watson Lake", "Yukon"],
["Taloyoak", "Nunavut"],
["Natashquan", "Quebec"],
["Buchans", "Newfoundland and Labrador"],
["Hall Beach", "Nunavut"],
["Arctic Bay", "Nunavut"],
["Fort Good Hope", "Northwest Territories"],
["Mingan", "Quebec"],
["Kangirsuk", "Quebec"],
["Sandspit", "British Columbia"],
["Delƒone", "Northwest Territories"],
["Fort Smith", "Northwest Territories"],
["Cartwright", "Newfoundland and Labrador"],
["Holman", "Northwest Territories"],
["Lynn Lake", "Manitoba"],
["Schefferville", "Quebec"],
["Trout River", "Newfoundland and Labrador"],
["Forteau Bay", "Newfoundland and Labrador"],
["Fort Resolution", "Northwest Territories"],
["Hopedale", "Newfoundland and Labrador"],
["Pukatawagan", "Manitoba"],
["Trepassey", "Newfoundland and Labrador"],
["Kimmirut", "Nunavut"],
["Chesterfield Inlet", "Nunavut"],
["Eastmain", "Quebec"],
["Dease Lake", "British Columbia"],
["Paulatuk", "Northwest Territories"],
["Fort Simpson", "Northwest Territories"],
["Brochet", "Manitoba"],
["Cat Lake", "Ontario"],
["Radisson", "Quebec"],
["Port-Menier", "Quebec"],
["Resolute", "Nunavut"],
["Saint Anthony", "Newfoundland and Labrador"],
["Port Hope Simpson", "Newfoundland and Labrador"],
["Oxford House", "Manitoba"],
["Tsiigehtchic", "Northwest Territories"],
["Ivujivik", "Quebec"],
["Stony Rapids", "Saskatchewan"],
["Alert", "Nunavut"],
["Fort Severn", "Ontario"],
["Rigolet", "Newfoundland and Labrador"],
["Lansdowne House", "Ontario"],
["Salluit", "Quebec"],
["Autselk Aoe", "Northwest Territories"],
["Uranium City", "Saskatchewan"],
["Burwash Landing", "Yukon"],
["Grise Fiord", "Nunavut"],
["Big Beaverhouse", "Ontario"],
["Island Lake", "Manitoba"],
["Ennadai", "Nunavut"]
]